/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HubRouteImport } from './routes/_hub'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PlayerRouteRouteImport } from './routes/player/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerIndexRouteImport } from './routes/player/index'
import { Route as PlayerOutputRouteImport } from './routes/player/output'
import { Route as HubTeamsRouteImport } from './routes/_hub/teams'
import { Route as HubSongsRouteImport } from './routes/_hub/songs'
import { Route as HubSettingsRouteImport } from './routes/_hub/settings'
import { Route as HubSetlistsRouteImport } from './routes/_hub/setlists'
import { Route as HubSessionsRouteImport } from './routes/_hub/sessions'
import { Route as HubCollectionsRouteImport } from './routes/_hub/collections'
import { Route as HubAboutRouteImport } from './routes/_hub/about'
import { Route as HubTeamsTeamIdRouteImport } from './routes/_hub/teams.$teamId'
import { Route as HubSongsSongIdRouteImport } from './routes/_hub/songs.$songId'
import { Route as HubSetlistsSetlistIdRouteImport } from './routes/_hub/setlists.$setlistId'
import { Route as HubCollectionsCollectionIdRouteImport } from './routes/_hub/collections.$collectionId'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/_hub',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRouteRoute = PlayerRouteRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerRouteRoute,
} as any)
const PlayerOutputRoute = PlayerOutputRouteImport.update({
  id: '/output',
  path: '/output',
  getParentRoute: () => PlayerRouteRoute,
} as any)
const HubTeamsRoute = HubTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => HubRoute,
} as any)
const HubSongsRoute = HubSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => HubRoute,
} as any)
const HubSettingsRoute = HubSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HubRoute,
} as any)
const HubSetlistsRoute = HubSetlistsRouteImport.update({
  id: '/setlists',
  path: '/setlists',
  getParentRoute: () => HubRoute,
} as any)
const HubSessionsRoute = HubSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => HubRoute,
} as any)
const HubCollectionsRoute = HubCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => HubRoute,
} as any)
const HubAboutRoute = HubAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HubRoute,
} as any)
const HubTeamsTeamIdRoute = HubTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => HubTeamsRoute,
} as any)
const HubSongsSongIdRoute = HubSongsSongIdRouteImport.update({
  id: '/$songId',
  path: '/$songId',
  getParentRoute: () => HubSongsRoute,
} as any)
const HubSetlistsSetlistIdRoute = HubSetlistsSetlistIdRouteImport.update({
  id: '/$setlistId',
  path: '/$setlistId',
  getParentRoute: () => HubSetlistsRoute,
} as any)
const HubCollectionsCollectionIdRoute =
  HubCollectionsCollectionIdRouteImport.update({
    id: '/$collectionId',
    path: '/$collectionId',
    getParentRoute: () => HubCollectionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/player': typeof PlayerRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/about': typeof HubAboutRoute
  '/collections': typeof HubCollectionsRouteWithChildren
  '/sessions': typeof HubSessionsRoute
  '/setlists': typeof HubSetlistsRouteWithChildren
  '/settings': typeof HubSettingsRoute
  '/songs': typeof HubSongsRouteWithChildren
  '/teams': typeof HubTeamsRouteWithChildren
  '/player/output': typeof PlayerOutputRoute
  '/player/': typeof PlayerIndexRoute
  '/collections/$collectionId': typeof HubCollectionsCollectionIdRoute
  '/setlists/$setlistId': typeof HubSetlistsSetlistIdRoute
  '/songs/$songId': typeof HubSongsSongIdRoute
  '/teams/$teamId': typeof HubTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/about': typeof HubAboutRoute
  '/collections': typeof HubCollectionsRouteWithChildren
  '/sessions': typeof HubSessionsRoute
  '/setlists': typeof HubSetlistsRouteWithChildren
  '/settings': typeof HubSettingsRoute
  '/songs': typeof HubSongsRouteWithChildren
  '/teams': typeof HubTeamsRouteWithChildren
  '/player/output': typeof PlayerOutputRoute
  '/player': typeof PlayerIndexRoute
  '/collections/$collectionId': typeof HubCollectionsCollectionIdRoute
  '/setlists/$setlistId': typeof HubSetlistsSetlistIdRoute
  '/songs/$songId': typeof HubSongsSongIdRoute
  '/teams/$teamId': typeof HubTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/player': typeof PlayerRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_hub': typeof HubRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_hub/about': typeof HubAboutRoute
  '/_hub/collections': typeof HubCollectionsRouteWithChildren
  '/_hub/sessions': typeof HubSessionsRoute
  '/_hub/setlists': typeof HubSetlistsRouteWithChildren
  '/_hub/settings': typeof HubSettingsRoute
  '/_hub/songs': typeof HubSongsRouteWithChildren
  '/_hub/teams': typeof HubTeamsRouteWithChildren
  '/player/output': typeof PlayerOutputRoute
  '/player/': typeof PlayerIndexRoute
  '/_hub/collections/$collectionId': typeof HubCollectionsCollectionIdRoute
  '/_hub/setlists/$setlistId': typeof HubSetlistsSetlistIdRoute
  '/_hub/songs/$songId': typeof HubSongsSongIdRoute
  '/_hub/teams/$teamId': typeof HubTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/player'
    | '/$'
    | '/join'
    | '/login'
    | '/logout'
    | '/about'
    | '/collections'
    | '/sessions'
    | '/setlists'
    | '/settings'
    | '/songs'
    | '/teams'
    | '/player/output'
    | '/player/'
    | '/collections/$collectionId'
    | '/setlists/$setlistId'
    | '/songs/$songId'
    | '/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/join'
    | '/login'
    | '/logout'
    | '/about'
    | '/collections'
    | '/sessions'
    | '/setlists'
    | '/settings'
    | '/songs'
    | '/teams'
    | '/player/output'
    | '/player'
    | '/collections/$collectionId'
    | '/setlists/$setlistId'
    | '/songs/$songId'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/player'
    | '/$'
    | '/_hub'
    | '/join'
    | '/login'
    | '/logout'
    | '/_hub/about'
    | '/_hub/collections'
    | '/_hub/sessions'
    | '/_hub/setlists'
    | '/_hub/settings'
    | '/_hub/songs'
    | '/_hub/teams'
    | '/player/output'
    | '/player/'
    | '/_hub/collections/$collectionId'
    | '/_hub/setlists/$setlistId'
    | '/_hub/songs/$songId'
    | '/_hub/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerRouteRoute: typeof PlayerRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  HubRoute: typeof HubRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub': {
      id: '/_hub'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof PlayerRouteRoute
    }
    '/player/output': {
      id: '/player/output'
      path: '/output'
      fullPath: '/player/output'
      preLoaderRoute: typeof PlayerOutputRouteImport
      parentRoute: typeof PlayerRouteRoute
    }
    '/_hub/teams': {
      id: '/_hub/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof HubTeamsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/songs': {
      id: '/_hub/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof HubSongsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/settings': {
      id: '/_hub/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof HubSettingsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/setlists': {
      id: '/_hub/setlists'
      path: '/setlists'
      fullPath: '/setlists'
      preLoaderRoute: typeof HubSetlistsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/sessions': {
      id: '/_hub/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof HubSessionsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/collections': {
      id: '/_hub/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof HubCollectionsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/about': {
      id: '/_hub/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HubAboutRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/teams/$teamId': {
      id: '/_hub/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof HubTeamsTeamIdRouteImport
      parentRoute: typeof HubTeamsRoute
    }
    '/_hub/songs/$songId': {
      id: '/_hub/songs/$songId'
      path: '/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof HubSongsSongIdRouteImport
      parentRoute: typeof HubSongsRoute
    }
    '/_hub/setlists/$setlistId': {
      id: '/_hub/setlists/$setlistId'
      path: '/$setlistId'
      fullPath: '/setlists/$setlistId'
      preLoaderRoute: typeof HubSetlistsSetlistIdRouteImport
      parentRoute: typeof HubSetlistsRoute
    }
    '/_hub/collections/$collectionId': {
      id: '/_hub/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof HubCollectionsCollectionIdRouteImport
      parentRoute: typeof HubCollectionsRoute
    }
  }
}

interface PlayerRouteRouteChildren {
  PlayerOutputRoute: typeof PlayerOutputRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
}

const PlayerRouteRouteChildren: PlayerRouteRouteChildren = {
  PlayerOutputRoute: PlayerOutputRoute,
  PlayerIndexRoute: PlayerIndexRoute,
}

const PlayerRouteRouteWithChildren = PlayerRouteRoute._addFileChildren(
  PlayerRouteRouteChildren,
)

interface HubCollectionsRouteChildren {
  HubCollectionsCollectionIdRoute: typeof HubCollectionsCollectionIdRoute
}

const HubCollectionsRouteChildren: HubCollectionsRouteChildren = {
  HubCollectionsCollectionIdRoute: HubCollectionsCollectionIdRoute,
}

const HubCollectionsRouteWithChildren = HubCollectionsRoute._addFileChildren(
  HubCollectionsRouteChildren,
)

interface HubSetlistsRouteChildren {
  HubSetlistsSetlistIdRoute: typeof HubSetlistsSetlistIdRoute
}

const HubSetlistsRouteChildren: HubSetlistsRouteChildren = {
  HubSetlistsSetlistIdRoute: HubSetlistsSetlistIdRoute,
}

const HubSetlistsRouteWithChildren = HubSetlistsRoute._addFileChildren(
  HubSetlistsRouteChildren,
)

interface HubSongsRouteChildren {
  HubSongsSongIdRoute: typeof HubSongsSongIdRoute
}

const HubSongsRouteChildren: HubSongsRouteChildren = {
  HubSongsSongIdRoute: HubSongsSongIdRoute,
}

const HubSongsRouteWithChildren = HubSongsRoute._addFileChildren(
  HubSongsRouteChildren,
)

interface HubTeamsRouteChildren {
  HubTeamsTeamIdRoute: typeof HubTeamsTeamIdRoute
}

const HubTeamsRouteChildren: HubTeamsRouteChildren = {
  HubTeamsTeamIdRoute: HubTeamsTeamIdRoute,
}

const HubTeamsRouteWithChildren = HubTeamsRoute._addFileChildren(
  HubTeamsRouteChildren,
)

interface HubRouteChildren {
  HubAboutRoute: typeof HubAboutRoute
  HubCollectionsRoute: typeof HubCollectionsRouteWithChildren
  HubSessionsRoute: typeof HubSessionsRoute
  HubSetlistsRoute: typeof HubSetlistsRouteWithChildren
  HubSettingsRoute: typeof HubSettingsRoute
  HubSongsRoute: typeof HubSongsRouteWithChildren
  HubTeamsRoute: typeof HubTeamsRouteWithChildren
}

const HubRouteChildren: HubRouteChildren = {
  HubAboutRoute: HubAboutRoute,
  HubCollectionsRoute: HubCollectionsRouteWithChildren,
  HubSessionsRoute: HubSessionsRoute,
  HubSetlistsRoute: HubSetlistsRouteWithChildren,
  HubSettingsRoute: HubSettingsRoute,
  HubSongsRoute: HubSongsRouteWithChildren,
  HubTeamsRoute: HubTeamsRouteWithChildren,
}

const HubRouteWithChildren = HubRoute._addFileChildren(HubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerRouteRoute: PlayerRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  HubRoute: HubRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
