/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HubRouteImport } from './routes/_hub'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PlayerRouteRouteImport } from './routes/player/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerIndexRouteImport } from './routes/player/index'
import { Route as PlayerOutputRouteImport } from './routes/player/output'
import { Route as PlayerRoomsInviteRouteImport } from './routes/player-rooms.invite'
import { Route as HubUgcRouteImport } from './routes/_hub/ugc'
import { Route as HubTermsRouteImport } from './routes/_hub/terms'
import { Route as HubTeamsRouteImport } from './routes/_hub/teams'
import { Route as HubSongsRouteImport } from './routes/_hub/songs'
import { Route as HubSettingsRouteImport } from './routes/_hub/settings'
import { Route as HubSetlistsRouteImport } from './routes/_hub/setlists'
import { Route as HubSessionsRouteImport } from './routes/_hub/sessions'
import { Route as HubPrivacyRouteImport } from './routes/_hub/privacy'
import { Route as HubPlayerRoomsRouteImport } from './routes/_hub/player-rooms'
import { Route as HubCollectionsRouteImport } from './routes/_hub/collections'
import { Route as HubAdminRouteImport } from './routes/_hub/admin'
import { Route as HubAboutRouteImport } from './routes/_hub/about'
import { Route as PlayerRoomsInviteIndexRouteImport } from './routes/player-rooms.invite.index'
import { Route as PlayerRoomRoomIdRouteImport } from './routes/player/room.$roomId'
import { Route as PlayerRoomsInviteRoomIdRouteImport } from './routes/player-rooms.invite.$roomId'
import { Route as HubTeamsTeamIdRouteImport } from './routes/_hub/teams.$teamId'
import { Route as HubSongsSongIdRouteImport } from './routes/_hub/songs.$songId'
import { Route as HubSetlistsSetlistIdRouteImport } from './routes/_hub/setlists.$setlistId'
import { Route as HubCollectionsCollectionIdRouteImport } from './routes/_hub/collections.$collectionId'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/_hub',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRouteRoute = PlayerRouteRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerRouteRoute,
} as any)
const PlayerOutputRoute = PlayerOutputRouteImport.update({
  id: '/output',
  path: '/output',
  getParentRoute: () => PlayerRouteRoute,
} as any)
const PlayerRoomsInviteRoute = PlayerRoomsInviteRouteImport.update({
  id: '/player-rooms/invite',
  path: '/player-rooms/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const HubUgcRoute = HubUgcRouteImport.update({
  id: '/ugc',
  path: '/ugc',
  getParentRoute: () => HubRoute,
} as any)
const HubTermsRoute = HubTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => HubRoute,
} as any)
const HubTeamsRoute = HubTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => HubRoute,
} as any)
const HubSongsRoute = HubSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => HubRoute,
} as any)
const HubSettingsRoute = HubSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HubRoute,
} as any)
const HubSetlistsRoute = HubSetlistsRouteImport.update({
  id: '/setlists',
  path: '/setlists',
  getParentRoute: () => HubRoute,
} as any)
const HubSessionsRoute = HubSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => HubRoute,
} as any)
const HubPrivacyRoute = HubPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => HubRoute,
} as any)
const HubPlayerRoomsRoute = HubPlayerRoomsRouteImport.update({
  id: '/player-rooms',
  path: '/player-rooms',
  getParentRoute: () => HubRoute,
} as any)
const HubCollectionsRoute = HubCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => HubRoute,
} as any)
const HubAdminRoute = HubAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => HubRoute,
} as any)
const HubAboutRoute = HubAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HubRoute,
} as any)
const PlayerRoomsInviteIndexRoute = PlayerRoomsInviteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerRoomsInviteRoute,
} as any)
const PlayerRoomRoomIdRoute = PlayerRoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => PlayerRouteRoute,
} as any)
const PlayerRoomsInviteRoomIdRoute = PlayerRoomsInviteRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => PlayerRoomsInviteRoute,
} as any)
const HubTeamsTeamIdRoute = HubTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => HubTeamsRoute,
} as any)
const HubSongsSongIdRoute = HubSongsSongIdRouteImport.update({
  id: '/$songId',
  path: '/$songId',
  getParentRoute: () => HubSongsRoute,
} as any)
const HubSetlistsSetlistIdRoute = HubSetlistsSetlistIdRouteImport.update({
  id: '/$setlistId',
  path: '/$setlistId',
  getParentRoute: () => HubSetlistsRoute,
} as any)
const HubCollectionsCollectionIdRoute =
  HubCollectionsCollectionIdRouteImport.update({
    id: '/$collectionId',
    path: '/$collectionId',
    getParentRoute: () => HubCollectionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/player': typeof PlayerRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/about': typeof HubAboutRoute
  '/admin': typeof HubAdminRoute
  '/collections': typeof HubCollectionsRouteWithChildren
  '/player-rooms': typeof HubPlayerRoomsRoute
  '/privacy': typeof HubPrivacyRoute
  '/sessions': typeof HubSessionsRoute
  '/setlists': typeof HubSetlistsRouteWithChildren
  '/settings': typeof HubSettingsRoute
  '/songs': typeof HubSongsRouteWithChildren
  '/teams': typeof HubTeamsRouteWithChildren
  '/terms': typeof HubTermsRoute
  '/ugc': typeof HubUgcRoute
  '/player-rooms/invite': typeof PlayerRoomsInviteRouteWithChildren
  '/player/output': typeof PlayerOutputRoute
  '/player/': typeof PlayerIndexRoute
  '/collections/$collectionId': typeof HubCollectionsCollectionIdRoute
  '/setlists/$setlistId': typeof HubSetlistsSetlistIdRoute
  '/songs/$songId': typeof HubSongsSongIdRoute
  '/teams/$teamId': typeof HubTeamsTeamIdRoute
  '/player-rooms/invite/$roomId': typeof PlayerRoomsInviteRoomIdRoute
  '/player/room/$roomId': typeof PlayerRoomRoomIdRoute
  '/player-rooms/invite/': typeof PlayerRoomsInviteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/about': typeof HubAboutRoute
  '/admin': typeof HubAdminRoute
  '/collections': typeof HubCollectionsRouteWithChildren
  '/player-rooms': typeof HubPlayerRoomsRoute
  '/privacy': typeof HubPrivacyRoute
  '/sessions': typeof HubSessionsRoute
  '/setlists': typeof HubSetlistsRouteWithChildren
  '/settings': typeof HubSettingsRoute
  '/songs': typeof HubSongsRouteWithChildren
  '/teams': typeof HubTeamsRouteWithChildren
  '/terms': typeof HubTermsRoute
  '/ugc': typeof HubUgcRoute
  '/player/output': typeof PlayerOutputRoute
  '/player': typeof PlayerIndexRoute
  '/collections/$collectionId': typeof HubCollectionsCollectionIdRoute
  '/setlists/$setlistId': typeof HubSetlistsSetlistIdRoute
  '/songs/$songId': typeof HubSongsSongIdRoute
  '/teams/$teamId': typeof HubTeamsTeamIdRoute
  '/player-rooms/invite/$roomId': typeof PlayerRoomsInviteRoomIdRoute
  '/player/room/$roomId': typeof PlayerRoomRoomIdRoute
  '/player-rooms/invite': typeof PlayerRoomsInviteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/player': typeof PlayerRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_hub': typeof HubRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_hub/about': typeof HubAboutRoute
  '/_hub/admin': typeof HubAdminRoute
  '/_hub/collections': typeof HubCollectionsRouteWithChildren
  '/_hub/player-rooms': typeof HubPlayerRoomsRoute
  '/_hub/privacy': typeof HubPrivacyRoute
  '/_hub/sessions': typeof HubSessionsRoute
  '/_hub/setlists': typeof HubSetlistsRouteWithChildren
  '/_hub/settings': typeof HubSettingsRoute
  '/_hub/songs': typeof HubSongsRouteWithChildren
  '/_hub/teams': typeof HubTeamsRouteWithChildren
  '/_hub/terms': typeof HubTermsRoute
  '/_hub/ugc': typeof HubUgcRoute
  '/player-rooms/invite': typeof PlayerRoomsInviteRouteWithChildren
  '/player/output': typeof PlayerOutputRoute
  '/player/': typeof PlayerIndexRoute
  '/_hub/collections/$collectionId': typeof HubCollectionsCollectionIdRoute
  '/_hub/setlists/$setlistId': typeof HubSetlistsSetlistIdRoute
  '/_hub/songs/$songId': typeof HubSongsSongIdRoute
  '/_hub/teams/$teamId': typeof HubTeamsTeamIdRoute
  '/player-rooms/invite/$roomId': typeof PlayerRoomsInviteRoomIdRoute
  '/player/room/$roomId': typeof PlayerRoomRoomIdRoute
  '/player-rooms/invite/': typeof PlayerRoomsInviteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/player'
    | '/$'
    | '/join'
    | '/login'
    | '/logout'
    | '/about'
    | '/admin'
    | '/collections'
    | '/player-rooms'
    | '/privacy'
    | '/sessions'
    | '/setlists'
    | '/settings'
    | '/songs'
    | '/teams'
    | '/terms'
    | '/ugc'
    | '/player-rooms/invite'
    | '/player/output'
    | '/player/'
    | '/collections/$collectionId'
    | '/setlists/$setlistId'
    | '/songs/$songId'
    | '/teams/$teamId'
    | '/player-rooms/invite/$roomId'
    | '/player/room/$roomId'
    | '/player-rooms/invite/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/join'
    | '/login'
    | '/logout'
    | '/about'
    | '/admin'
    | '/collections'
    | '/player-rooms'
    | '/privacy'
    | '/sessions'
    | '/setlists'
    | '/settings'
    | '/songs'
    | '/teams'
    | '/terms'
    | '/ugc'
    | '/player/output'
    | '/player'
    | '/collections/$collectionId'
    | '/setlists/$setlistId'
    | '/songs/$songId'
    | '/teams/$teamId'
    | '/player-rooms/invite/$roomId'
    | '/player/room/$roomId'
    | '/player-rooms/invite'
  id:
    | '__root__'
    | '/'
    | '/player'
    | '/$'
    | '/_hub'
    | '/join'
    | '/login'
    | '/logout'
    | '/_hub/about'
    | '/_hub/admin'
    | '/_hub/collections'
    | '/_hub/player-rooms'
    | '/_hub/privacy'
    | '/_hub/sessions'
    | '/_hub/setlists'
    | '/_hub/settings'
    | '/_hub/songs'
    | '/_hub/teams'
    | '/_hub/terms'
    | '/_hub/ugc'
    | '/player-rooms/invite'
    | '/player/output'
    | '/player/'
    | '/_hub/collections/$collectionId'
    | '/_hub/setlists/$setlistId'
    | '/_hub/songs/$songId'
    | '/_hub/teams/$teamId'
    | '/player-rooms/invite/$roomId'
    | '/player/room/$roomId'
    | '/player-rooms/invite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerRouteRoute: typeof PlayerRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  HubRoute: typeof HubRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PlayerRoomsInviteRoute: typeof PlayerRoomsInviteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub': {
      id: '/_hub'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof PlayerRouteRoute
    }
    '/player/output': {
      id: '/player/output'
      path: '/output'
      fullPath: '/player/output'
      preLoaderRoute: typeof PlayerOutputRouteImport
      parentRoute: typeof PlayerRouteRoute
    }
    '/player-rooms/invite': {
      id: '/player-rooms/invite'
      path: '/player-rooms/invite'
      fullPath: '/player-rooms/invite'
      preLoaderRoute: typeof PlayerRoomsInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub/ugc': {
      id: '/_hub/ugc'
      path: '/ugc'
      fullPath: '/ugc'
      preLoaderRoute: typeof HubUgcRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/terms': {
      id: '/_hub/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof HubTermsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/teams': {
      id: '/_hub/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof HubTeamsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/songs': {
      id: '/_hub/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof HubSongsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/settings': {
      id: '/_hub/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof HubSettingsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/setlists': {
      id: '/_hub/setlists'
      path: '/setlists'
      fullPath: '/setlists'
      preLoaderRoute: typeof HubSetlistsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/sessions': {
      id: '/_hub/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof HubSessionsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/privacy': {
      id: '/_hub/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof HubPrivacyRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/player-rooms': {
      id: '/_hub/player-rooms'
      path: '/player-rooms'
      fullPath: '/player-rooms'
      preLoaderRoute: typeof HubPlayerRoomsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/collections': {
      id: '/_hub/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof HubCollectionsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/admin': {
      id: '/_hub/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof HubAdminRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/about': {
      id: '/_hub/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HubAboutRouteImport
      parentRoute: typeof HubRoute
    }
    '/player-rooms/invite/': {
      id: '/player-rooms/invite/'
      path: '/'
      fullPath: '/player-rooms/invite/'
      preLoaderRoute: typeof PlayerRoomsInviteIndexRouteImport
      parentRoute: typeof PlayerRoomsInviteRoute
    }
    '/player/room/$roomId': {
      id: '/player/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/player/room/$roomId'
      preLoaderRoute: typeof PlayerRoomRoomIdRouteImport
      parentRoute: typeof PlayerRouteRoute
    }
    '/player-rooms/invite/$roomId': {
      id: '/player-rooms/invite/$roomId'
      path: '/$roomId'
      fullPath: '/player-rooms/invite/$roomId'
      preLoaderRoute: typeof PlayerRoomsInviteRoomIdRouteImport
      parentRoute: typeof PlayerRoomsInviteRoute
    }
    '/_hub/teams/$teamId': {
      id: '/_hub/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof HubTeamsTeamIdRouteImport
      parentRoute: typeof HubTeamsRoute
    }
    '/_hub/songs/$songId': {
      id: '/_hub/songs/$songId'
      path: '/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof HubSongsSongIdRouteImport
      parentRoute: typeof HubSongsRoute
    }
    '/_hub/setlists/$setlistId': {
      id: '/_hub/setlists/$setlistId'
      path: '/$setlistId'
      fullPath: '/setlists/$setlistId'
      preLoaderRoute: typeof HubSetlistsSetlistIdRouteImport
      parentRoute: typeof HubSetlistsRoute
    }
    '/_hub/collections/$collectionId': {
      id: '/_hub/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof HubCollectionsCollectionIdRouteImport
      parentRoute: typeof HubCollectionsRoute
    }
  }
}

interface PlayerRouteRouteChildren {
  PlayerOutputRoute: typeof PlayerOutputRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
  PlayerRoomRoomIdRoute: typeof PlayerRoomRoomIdRoute
}

const PlayerRouteRouteChildren: PlayerRouteRouteChildren = {
  PlayerOutputRoute: PlayerOutputRoute,
  PlayerIndexRoute: PlayerIndexRoute,
  PlayerRoomRoomIdRoute: PlayerRoomRoomIdRoute,
}

const PlayerRouteRouteWithChildren = PlayerRouteRoute._addFileChildren(
  PlayerRouteRouteChildren,
)

interface HubCollectionsRouteChildren {
  HubCollectionsCollectionIdRoute: typeof HubCollectionsCollectionIdRoute
}

const HubCollectionsRouteChildren: HubCollectionsRouteChildren = {
  HubCollectionsCollectionIdRoute: HubCollectionsCollectionIdRoute,
}

const HubCollectionsRouteWithChildren = HubCollectionsRoute._addFileChildren(
  HubCollectionsRouteChildren,
)

interface HubSetlistsRouteChildren {
  HubSetlistsSetlistIdRoute: typeof HubSetlistsSetlistIdRoute
}

const HubSetlistsRouteChildren: HubSetlistsRouteChildren = {
  HubSetlistsSetlistIdRoute: HubSetlistsSetlistIdRoute,
}

const HubSetlistsRouteWithChildren = HubSetlistsRoute._addFileChildren(
  HubSetlistsRouteChildren,
)

interface HubSongsRouteChildren {
  HubSongsSongIdRoute: typeof HubSongsSongIdRoute
}

const HubSongsRouteChildren: HubSongsRouteChildren = {
  HubSongsSongIdRoute: HubSongsSongIdRoute,
}

const HubSongsRouteWithChildren = HubSongsRoute._addFileChildren(
  HubSongsRouteChildren,
)

interface HubTeamsRouteChildren {
  HubTeamsTeamIdRoute: typeof HubTeamsTeamIdRoute
}

const HubTeamsRouteChildren: HubTeamsRouteChildren = {
  HubTeamsTeamIdRoute: HubTeamsTeamIdRoute,
}

const HubTeamsRouteWithChildren = HubTeamsRoute._addFileChildren(
  HubTeamsRouteChildren,
)

interface HubRouteChildren {
  HubAboutRoute: typeof HubAboutRoute
  HubAdminRoute: typeof HubAdminRoute
  HubCollectionsRoute: typeof HubCollectionsRouteWithChildren
  HubPlayerRoomsRoute: typeof HubPlayerRoomsRoute
  HubPrivacyRoute: typeof HubPrivacyRoute
  HubSessionsRoute: typeof HubSessionsRoute
  HubSetlistsRoute: typeof HubSetlistsRouteWithChildren
  HubSettingsRoute: typeof HubSettingsRoute
  HubSongsRoute: typeof HubSongsRouteWithChildren
  HubTeamsRoute: typeof HubTeamsRouteWithChildren
  HubTermsRoute: typeof HubTermsRoute
  HubUgcRoute: typeof HubUgcRoute
}

const HubRouteChildren: HubRouteChildren = {
  HubAboutRoute: HubAboutRoute,
  HubAdminRoute: HubAdminRoute,
  HubCollectionsRoute: HubCollectionsRouteWithChildren,
  HubPlayerRoomsRoute: HubPlayerRoomsRoute,
  HubPrivacyRoute: HubPrivacyRoute,
  HubSessionsRoute: HubSessionsRoute,
  HubSetlistsRoute: HubSetlistsRouteWithChildren,
  HubSettingsRoute: HubSettingsRoute,
  HubSongsRoute: HubSongsRouteWithChildren,
  HubTeamsRoute: HubTeamsRouteWithChildren,
  HubTermsRoute: HubTermsRoute,
  HubUgcRoute: HubUgcRoute,
}

const HubRouteWithChildren = HubRoute._addFileChildren(HubRouteChildren)

interface PlayerRoomsInviteRouteChildren {
  PlayerRoomsInviteRoomIdRoute: typeof PlayerRoomsInviteRoomIdRoute
  PlayerRoomsInviteIndexRoute: typeof PlayerRoomsInviteIndexRoute
}

const PlayerRoomsInviteRouteChildren: PlayerRoomsInviteRouteChildren = {
  PlayerRoomsInviteRoomIdRoute: PlayerRoomsInviteRoomIdRoute,
  PlayerRoomsInviteIndexRoute: PlayerRoomsInviteIndexRoute,
}

const PlayerRoomsInviteRouteWithChildren =
  PlayerRoomsInviteRoute._addFileChildren(PlayerRoomsInviteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerRouteRoute: PlayerRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  HubRoute: HubRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PlayerRoomsInviteRoute: PlayerRoomsInviteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
